services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER:-admin}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:?Please configure DATABASE_PASSWORD in the .env file}"
      POSTGRES_DB: "watchdog"

  adminer:
    image: "adminer"
    restart: "always"
    ports:
      - 8080:8080
